server:
  port: 40713
  servlet:
    context-path: /rest

spring:
  application:
    name: mim-rest
  profiles:
    active: dev

mybatis-plus:
  #  configuration:
  mapper-locations: classpath*:mapper/**/*.xml